# Étape 1 : build
FROM maven:3.9.6-eclipse-temurin-21 AS builder

WORKDIR /app

COPY pom.xml mvnw ./
COPY .mvn .mvn

RUN ./mvnw dependency:go-offline

COPY src src

EXPOSE 8080

CMD [ "./mvnw", "spring-boot:run", "-Dspring-boot.run.profiles=dev" ]
