FROM node:22-alpine

WORKDIR /app

# Copier uniquement package.json et yarn.lock pour installer les dépendances
COPY package.json yarn.lock ./
RUN yarn install
RUN yarn global add nodemon

# Copier le reste du code
COPY . .

EXPOSE 3001

# Nodemon sur server.js
CMD ["nodemon", "--watch", ".", "--ext", "js,ts", "server.js"]
